### ISSUE TITLE
syslog plugin is unable to collect data 

### ISSUE THREAD

**Issue by sachinkademane** [dishmael/snap-plugin-collector-syslog#1]
i loaded syslog plugin in centos 7....and my syslog deamon is running....when i start my syslog task to collect metrics to a file i can see null displaying in file....when i do snaptel task watch nothing is showing there....what might be the issue here?
my task file looks like below
```
---
  version: 1
  schedule:
    type: "simple"
    interval: "1s"
  max-failures: 10
  workflow:
    collect:
      config:
        /opsvision/syslog:
          port: 1514
          bufsize: 1024
      metrics:
        /opsvision/syslog/counter: {}
        /opsvision/syslog/event/*/summary: {}
        /opsvision/syslog/event/*/message: {}
      publish:
        - plugin_name: "file"
          config:
            file: "/tmp/syslog_metrics.log"

```
